### ISSUE TITLE
Error: stub(obj, 'meth', fn) has been removed, see documentation

### ISSUE THREAD

**Issue by fishcharlie** [gdnmobilelab/mock-aws-sinon#5]
I'm getting the following error when trying to use this package.

```
  TypeError: stub(obj, 'meth', fn) has been removed, see documentation
      at stub (node_modules/sinon/lib/sinon/stub.js:25:15)
      at Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:291:33)
      at stub (node_modules/mock-aws-sinon/index.js:20:15)
      at stubRequestSend (node_modules/mock-aws-sinon/index.js:68:5)
      at module.exports (node_modules/mock-aws-sinon/index.js:87:5)
```

**Comment by alemuro** [comment]
You can install a previous version of `sinon`. I tried the recommended one (4.1.3) and it works now:

```
$ npm install --save-dev sinon@4.1.3
```

**Comment by andrewhiles** [comment]
Thanks @alemuro - this saved me a lot of time :)

**Comment by LuisSanchez** [comment]
I should not recommend downgrading your version, instead you can do something like this:

```
let stub = sinon.stub(obj, "meth").callsFake(() => {
      return {
        meth2: sinon.stub().callsFake(() => {
          return {
            meth3: sinon.stub().returns(yourFixture),
          };
        }),
      };
    });
```

**Comment by dbrenot-pelmorex** [comment]
I've fixed this in the PR that I just made. If it's merged you will be able to easily use the newest version of sinon.
